### ISSUE TITLE
load device to set ice server option missing (available in android/ web)

### ISSUE THREAD

**Issue by lets-swapcode** [VLprojects/mediasoup-client-swift#14]
Our repo - device.load(with: rtpCapabilities)
Android, web repo has extra parameters to set ICE server configuration - check last load function

`
 code

            for (i in 0 until mIceServers!!.length()) {
                val server = mIceServers!!.getJSONObject(i)
                var iceServer = IceServer(
                    server.getString("urls"),
                    server.getString("username"),
                    server.getString("credential")
                )
                serverList.add(iceServer)
            }
            val rtcConfiguration = RTCConfiguration(serverList)
            if (icePolicy == "relay") rtcConfiguration.iceTransportsType =
                org.webrtc.PeerConnection.IceTransportsType.RELAY
            mOptions!!.setRTCConfig(rtcConfiguration)
            mJMMediaDevice?.load(rtpCapabilities.toString(), mOptions)
`

so how to set ice server in iOS? 
I can see send transport has few functions. 
`
code

    public func restartICE(with iceParameters: String) throws
    public func updateICEServers(_ iceServers: String) throws
    public func updateICETransportPolicy(_ transportPolicy: Mediasoup.ICETransportPolicy) throws
`

Question 
1. What is the right way to set ice server like android?
2. Will updateICEServer work? do we need to call restartICE as well? 
Note - I tried this too. server is not receiving any ice server info. please help.

**Comment by lets-swapcode** [comment]
[update] 

We checked the source code for swift wrapper. class device wrapper.mm. 

The function load device does not have the peer connection parameter and it is taking default one which you have initialised in init. 

`device wrapper.mm

(void) loadWithRouterRTPCapabilities:(NSString *) routerRTPCapabilities error:(out NSError *__autoreleasing _Nullable *_Nullable)error {

	mediasoupTry(^{
		auto routerRTPCapabilitiesString = std::string(routerRTPCapabilities.UTF8String);
		auto routerRTPCapabilitiesJSON = nlohmann::json::parse(routerRTPCapabilitiesString);
		self->_device->Load(routerRTPCapabilitiesJSON, self->_pcOptions);
	}, error);
}
`

please expose/ add this parameter in the function itself so that I can pass the server list.

**Comment by HarshSurati-Jio** [comment]
[update] 

We have clone the project and have added the missing implementation for the peerConnection options.

It is working fine.

**Comment by lets-swapcode** [comment]
[update] 

We cloned the project and added the missing implementation for peer connection options. 

We are testing it for few days now, it is working fine.

**Comment by fedulvtubudul** [comment]
You should remember that `mediasoup-client-swift` is just a wrapper on top of `libmediasoupclient`. Each time we change something in the API it makes harder to keep it in sync when `libmediasoupclient` is updated. Thats why I don't want to add something that is not available in the C++ version of libemediasoupclient.

If we look at the TypeScript implementation of the mediasoup client, they have the `iceServers` and `iceTransportPolicy` parameters when creating a transport. C++ version of the `libmediasoupclient` does not have these parameters. Thats why Swift wrapper does not have them as well.

So what's really need to be done in the first place is to implement these parameters in C++ library. I've created an issue on the original library repo and will try to make what you suggest, but it will take time.

Closing this issue as it's not a problem of wrapper itself and [issue in libmediasoupclient ](https://github.com/versatica/libmediasoupclient/issues/165) will be more relevant.

**Comment by fedulvtubudul** [comment]
@lets-swapcode next day I finally realised what you've actually meant 😅. And yep, that parameter should be added on mediasoup-client-swift side.

**Comment by lets-swapcode** [comment]
hey, I have created pull request for the same. 

https://github.com/VLprojects/mediasoup-client-swift/pull/16

**Comment by fedulvtubudul** [comment]
Please check version 0.4.2. I've added parameters you need into `Device` methods `createSendTransport` and `createReceiveTransport`. Please tell if it solves your task with ICE servers configuration.

I've seen your PR and really appreciate your help. But I see couple of issues with that PR. 

First of all it may not work with some ICE server configurations. As [docs says](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer), `username` and `credentials` parameters are optional, and `urls` can be "either a single string or an array of strings". So beware of that if you use the code you've submitted in this PR.

Second thing that is not an issue by itself, but can become such in future. You've added a new parameter to the Device `load` method, witch does not exist in TS version of the mediasoup client. But developers of [libmediasoupclient](https://github.com/versatica/libmediasoupclient) and [mediasoup-client](https://github.com/versatica/mediasoup-client) use TS implementation as a reference, while C++ implementation is a "clone" which is supposed to be as close as possible to the TS version. All the other mediasoup clients are just wrappers on top of that two. So I suggest copying TS implementation API, not the Android or any other "secondary" implementation.

**Comment by lets-swapcode** [comment]
No, This is not working. 

I stashed my local changes on load device and used directly the pod. 

Added Iceservers and transportpolicy in create transport function.  

Here's the ice server object _(dummy object)_
"[\n  {\n    \"urls\" : \"turns:[xyz.com:000](http://xyz.com:0/)?transport=tcp\",\n    \"credential\" : \”password\”,\n    \"username\" : \”username\”\n  },\n  {\n    \"username\" : \"username\",\n    \"urls\" : \"turns:[xyz.com:000](http://xyz.com:0/)?transport=udp\”,\n    \"credential\" : \"password\"\n  }\n]"

`
try device?.createSendTransport(
                id: tuple.id,
                iceParameters: tuple.iceParameters,
                iceCandidates: tuple.iceCandidates,
                dtlsParameters: tuple.dtlsParameters,
                sctpParameters: nil,
                iceServers: tuple.iceServers,
                iceTransportPolicy: tuple.isRelayTransportPolicy ? .relay : .all,
                appData: nil
            )
`
