### ISSUE TITLE
Allow DeviceWrapper to support custom RTCAudioDevice

### ISSUE THREAD

**Issue by YoavGro** [VLprojects/mediasoup-client-swift#22]
Currently when creating a `Device` the SDK does the following:

`
	public init() {
		self.device = DeviceWrapper()
	}
`

Which in turn calls the init of the `DeviceWrapper`

In the init function the SDK creates the `RTCPeerConnection` by doing:

`
		auto pcFactoryBuilder = [[RTCPeerConnectionFactoryBuilder alloc] init];
		[pcFactoryBuilder setAudioEncoderFactory:audioEncoderFactory];
		[pcFactoryBuilder setAudioDecoderFactory:audioDecoderFactory];
		[pcFactoryBuilder setVideoEncoderFactory:std::move(videoEncoderFactory)];
		[pcFactoryBuilder setVideoDecoderFactory:std::move(videoDecoderFactory)];
		[pcFactoryBuilder setAudioDeviceModule:webrtc::CreateAudioDeviceModule()];
`

The line `[pcFactoryBuilder setAudioDeviceModule:webrtc::CreateAudioDeviceModule()];` creates a default RTCAudioDevice.

This prevents us from giving the RTC device a custom implementation of the `RTCAudioDevice`.

If possible we need to allow the `DeviceWrapper` to accept in it's initializer a `RTCAudioDevice` or a `RTCPeerConnectionFactory` from the Client app

Thanks

**Comment by fedulvtubudul** [comment]
Added `RTCPeerConnectionFactory` parameter to `Device` constructor in version 0.4.3.

**Comment by fedulvtubudul** [comment]
Version 0.4.3 was not actually doing what it should, please use 0.4.4.
