### ISSUE TITLE
No H264 decoding with 0.4.3

### ISSUE THREAD

**Issue by papaz0rgl** [VLprojects/mediasoup-client-swift#23]
Hello, 

I tried to upgrade from 0.4.2 to 0.4.3 but I'm not able to consume an H264 stream with 0.4.3 in the same setups that works perfectly with 0.4.2

When I look at the device.rtpCapabilities() there is no H264 codec. 

Any idea ?

**Comment by fedulvtubudul** [comment]
Yep, there was a typo in device initialization code. Using _pcFactory ivar before its actually set. Should be fixed in version 0.4.4.

**Comment by papaz0rgl** [comment]
I can confirm that it works, thanks 👍  (still no simulcast in H264 ...)
